#!/usr/bin/env python3
"""Generate runtime_health YAML thresholds from a known-good metrics CSV.

Enable logging while replaying a normal bag by temporarily setting
runtime_health/metrics_log_path in config/helios_bistu.yaml, for example:
  metrics_log_path: "/tmp/fast_lio_sam_runtime_health.csv"

Then run:
  roslaunch fast_lio_sam mapping_rs_bistu.launch use_sim_time:=true
  rosbag play --clock /media/whd/ITGZ_NOFAN/USED_ROSBAG_2512/2025-08-30-16-00-21.bag
  python3 scripts/calibrate_runtime_health.py /tmp/fast_lio_sam_runtime_health.csv
"""

import argparse
import csv
import math
import statistics
import sys


def finite_float(row, key):
    try:
        value = float(row[key])
    except (KeyError, TypeError, ValueError):
        return None
    return value if math.isfinite(value) else None


def percentile(values, q):
    if not values:
        return 0.0
    ordered = sorted(values)
    if len(ordered) == 1:
        return ordered[0]
    pos = (len(ordered) - 1) * q
    lo = int(math.floor(pos))
    hi = int(math.ceil(pos))
    if lo == hi:
        return ordered[lo]
    return ordered[lo] + (ordered[hi] - ordered[lo]) * (pos - lo)


def median_abs_deviation(values):
    if not values:
        return 0.0
    med = statistics.median(values)
    return statistics.median([abs(v - med) for v in values])


def load_metrics(path):
    rows = []
    with open(path, newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            rows.append(row)
    if not rows:
        raise RuntimeError(f"No rows found in {path}")
    return rows


def positive(values):
    return [v for v in values if v is not None and v > 0.0]


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("csv", help="CSV generated by runtime_health/metrics_log_path")
    parser.add_argument("--topic", default="/fast_lio_sam/runtime_health_alert")
    parser.add_argument("--bad-window-frames", type=int, default=5)
    parser.add_argument("--recover-window-frames", type=int, default=10)
    args = parser.parse_args()

    rows = load_metrics(args.csv)
    effective_nums = [finite_float(r, "effective_feature_num") for r in rows]
    ratios = [finite_float(r, "effective_feature_ratio") for r in rows]
    residuals = [finite_float(r, "residual_mean") for r in rows]
    translations = positive([finite_float(r, "delta_translation") for r in rows])
    yaws = positive([finite_float(r, "delta_yaw") for r in rows])
    speeds = positive([finite_float(r, "implied_speed") for r in rows])

    effective_nums = positive(effective_nums)
    ratios = positive(ratios)
    residuals = positive(residuals)

    if len(effective_nums) < 20 or len(ratios) < 20 or len(residuals) < 20:
        raise RuntimeError("Need at least 20 valid metric rows; replay more of the normal bag.")

    residual_med = statistics.median(residuals)
    residual_mad = median_abs_deviation(residuals)
    residual_warn = max(percentile(residuals, 0.99), residual_med + 6.0 * residual_mad)
    residual_error = max(residual_warn * 1.5, percentile(residuals, 0.999))

    min_feature_num = max(5, int(math.floor(percentile(effective_nums, 0.01) * 0.7)))
    min_ratio = max(0.005, percentile(ratios, 0.01) * 0.7)
    critical_ratio = max(0.001, min_ratio * 0.25)

    max_translation = max(0.5, percentile(translations, 0.999) * 2.0) if translations else 2.0
    max_yaw = max(0.2, percentile(yaws, 0.999) * 2.0) if yaws else 0.8
    max_speed = max(2.0, percentile(speeds, 0.999) * 2.0) if speeds else 8.0

    print("runtime_health:")
    print("    enable: true")
    print(f'    topic: "{args.topic}"')
    print("    repeat_active_alert_sec: 5.0")
    print(f"    bad_window_frames: {args.bad_window_frames}")
    print(f"    recover_window_frames: {args.recover_window_frames}")
    print(f"    min_effective_feature_num: {min_feature_num}")
    print(f"    min_effective_feature_ratio: {min_ratio:.6f}")
    print(f"    critical_effective_feature_ratio: {critical_ratio:.6f}")
    print(f"    max_residual_mean_warn: {residual_warn:.6f}")
    print(f"    max_residual_mean_error: {residual_error:.6f}")
    print(f"    max_frame_translation: {max_translation:.6f}")
    print(f"    max_frame_yaw: {max_yaw:.6f}")
    print(f"    max_implied_speed: {max_speed:.6f}")
    print("    flicker_window_frames: 6")
    print("    rollback_distance: 0.5")
    print("    loop_correction_grace_sec: 2.0")
    print('    metrics_log_path: ""')


if __name__ == "__main__":
    try:
        main()
    except Exception as exc:
        print(f"calibrate_runtime_health.py: {exc}", file=sys.stderr)
        sys.exit(1)
